name: deep_voice
description: Professional Voice Changer App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.1.0
  flutter_sound: ^10.1.0
  permission_handler: ^11.0.0
  flutter_ffmpeg: ^0.4.4
  provider: ^6.0.5
  confetti: ^0.7.0
  flutter_foreground_task: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/icons/
